name: Test and build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install dependencies (if needed)
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Run tests
        run: |
          make clean
          make test

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install dependencies (if needed)
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build and Install
        run: |
          make clean
          make
          make install
